sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ZkaaIMGIl+V4g4MRk8bm0KPb8qa3GmjOk25H2uliugo4pyF0BFb/JqjWWm8RQsarnANRHsaGqITr/6UvwGk1qNoG0oUxdeapMJoA0PLLoWyRlqlEod9zi6jrA0LGun6hoZZKgFU7h5QiPK3CQ+xfSKh+1hDZsidfiX4IDGrbEHKmVA2Qq12JrVhHokeNhwMExVl6ZT8gS/K9jIDrrTl8w+Jacu2AWIQOp44qho8VNfpSAKOVsvBVA8eX0VsPucsmr05fvzGHSnTypd2vQEWh5MYb+BUUD10buDrNzOHVg/lkUe2cH2mfwPXIgSls8ZUq06/p/U26b63ArGV9Ml8bi37xnCgYRWrN7aCuhdJN0Qvxj+F4fadwbiFMgrQVARDt5kJ/uJr6/zO8l2NMs1WpVPRObRrsFNuw255VW9bAkapkUu1CnBfCbuQyYPMKNJg7Vy3Ytml/cL7bGdlKqTovsU/TyxuObZ0L5o9lmWTtwRYSoIZKVaI7540gWwO0Txe25sWYuhvMR13o/Tloo9tljrP/ShPGAZpJQY5QSPvzDtLoxuhHybs/kddJufaPhq6vHU5Sj+R2JK5xjhyw4BX9mkAeQPw80WFE7AOfWqkCp3gs6kTR7VWgQLZlP80OWRXhRUd9eHFqoVKCB3bhgvcYReVzsY6YcUFZ2T0bwdf7dnc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Sisters-Volume-2_5462
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy